### ISSUE TITLE
User Registration Does Not Work

### ISSUE THREAD

**Issue by ghost** [Aareon/sarp-cad#17]
access_token.txt does not work

**Comment by Aareon** [comment]
What is your usage? You'll need to manually create an admin account in the database. From there you should be able to login with said account

**Comment by ghost** [comment]
Yes added myself to the DB set as admin, the access token I set with the .txt file shows underneath "generate new token" however when a user attempts to create an account it returns an error, unable to complete your request... does this require to create accounts manually for each user?

currently using bubble with 1000+ users in my current CAD solution, looking for better back end access, I like what you have made, I would love to talk about possibly making a custom solution

**Comment by Aareon** [comment]
You shouldn’t have to. I’ll double check that everything is functioning in a couple of hours, or fix what’s broken, either way. I’ll let you know what I find.

However, this project is incomplete and near abandoned. If you’re interested in helping out, though, feel free to do so.

**Comment by HarryjosephSARP** [comment]
Hi, can you display every error you have separate I’m having trouble finding what you’re having issues with and what errors you’re getting.

**Comment by hazzakak** [comment]
> Yes added myself to the DB set as admin, the access token I set with the .txt file shows underneath "generate new token" however when a user attempts to create an account it returns an error, unable to complete your request... does this require to create accounts manually for each user?
> 
> currently using bubble with 1000+ users in my current CAD solution, looking for better back end access, I like what you have made, I would love to talk about possibly making a custom solution

Hi, can you display every error you have separate I’m having trouble finding what you’re having issues with and what errors you’re getting?

**Comment by Aareon** [comment]
I'll leave this issue open another couple of days to give @LossRP an opportunity to get back to us. After that I'll close it as it seems to me to be a non-issue.
